### ISSUE TITLE
ImportError: cannot import name 'Tensor' from 'torch' (unknown location)

### ISSUE THREAD

**Issue by akshobhya95** [aangelopoulos/conformal-time-series#4]
Hi Aangelopoulos ,
                                I was trying to repro your code 'https://github.com/aangelopoulos/conformal-time-series' as suggested from the paper was trying to follow your steps as how you quoted:-
To reproduce the experiments in our paper, clone this repo and run the following code from the root directory.

conda create --name pid
pip install -r requirements.txt
cd tests
bash run_tests.sh
bash make_plots.sh

While triggering bash run_tests.sh I encounter import module issue here:-

Error Code Snippet:-
==============
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[106], line 7
      5 from core import standard_weighted_quantile, trailing_window, aci, aci_clipped, quantile, quantile_integrator_log, quantile_integrator_log_scorecaster
      6 from core.synthetic_scores import generate_scores
----> 7 from core.model_scores import generate_forecasts
      8 from datasets import load_dataset
      9 from darts import TimeSeries

File ~\Downloads\conformal-time-series\tests\..\core\model_scores.py:10
      8 from darts.models.forecasting.arima import ARIMA
      9 from darts.models.forecasting.theta import Theta
---> 10 from darts.models.forecasting.transformer_model import TransformerModel
     11 from darts import TimeSeries
     12 import pdb

File ~\anaconda3\lib\site-packages\darts\models\forecasting\transformer_model.py:13
     10 import torch.nn as nn
     12 from darts.logging import get_logger, raise_if, raise_if_not, raise_log
---> 13 from darts.models.components import glu_variants, layer_norm_variants
     14 from darts.models.components.glu_variants import GLU_FFN
     15 from darts.models.components.transformer import (
     16     CustomFeedForwardDecoderLayer,
     17     CustomFeedForwardEncoderLayer,
     18 )

File ~\anaconda3\lib\site-packages\darts\models\__init__.py:32
     29 from darts.models.utils import NotImportedModule
     31 try:
---> 32     from darts.models.forecasting.block_rnn_model import BlockRNNModel
     33     from darts.models.forecasting.dlinear import DLinearModel
     34     from darts.models.forecasting.global_baseline_models import (
     35         GlobalNaiveAggregate,
     36         GlobalNaiveDrift,
     37         GlobalNaiveSeasonal,
     38     )

File ~\anaconda3\lib\site-packages\darts\models\forecasting\block_rnn_model.py:14
     11 import torch.nn as nn
     13 from darts.logging import get_logger, raise_log
---> 14 from darts.models.forecasting.pl_forecasting_module import (
     15     PLPastCovariatesModule,
     16     io_processor,
     17 )
     18 from darts.models.forecasting.torch_forecasting_model import PastCovariatesTorchModel
     20 logger = get_logger(__name__)

File ~\anaconda3\lib\site-packages\darts\models\forecasting\pl_forecasting_module.py:9
      6 from functools import wraps
      7 from typing import Any, Dict, Optional, Sequence, Tuple, Union
----> 9 import pytorch_lightning as pl
     10 import torch
     11 import torch.nn as nn

File ~\anaconda3\lib\site-packages\pytorch_lightning\__init__.py:25
     22     _logger.addHandler(logging.StreamHandler())
     23     _logger.propagate = False
---> 25 from lightning_fabric.utilities.seed import seed_everything  # noqa: E402
     26 from lightning_fabric.utilities.warnings import disable_possible_user_warnings  # noqa: E402
     27 from pytorch_lightning.callbacks import Callback  # noqa: E402

File ~\anaconda3\lib\site-packages\lightning_fabric\__init__.py:30
     24 # In PyTorch 2.0+, setting this variable will force `torch.cuda.is_available()` and `torch.cuda.device_count()`
     25 # to use an NVML-based implementation that doesn't poison forks.
     26 # https://github.com/pytorch/pytorch/issues/83973
     27 os.environ["PYTORCH_NVML_BASED_CUDA_CHECK"] = "1"
---> 30 from lightning_fabric.fabric import Fabric  # noqa: E402
     31 from lightning_fabric.utilities.seed import seed_everything  # noqa: E402
     32 from lightning_fabric.utilities.warnings import disable_possible_user_warnings  # noqa: E402

File ~\anaconda3\lib\site-packages\lightning_fabric\fabric.py:39
     37 from lightning_utilities.core.apply_func import apply_to_collection
     38 from lightning_utilities.core.overrides import is_overridden
---> 39 from torch import Tensor
     40 from torch.optim import Optimizer
     41 from torch.utils.data import BatchSampler, DataLoader, DistributedSampler, RandomSampler, SequentialSampler

ImportError: cannot import name 'Tensor' from 'torch' (unknown location)

I was looking into similar issues over github but didn't find anything valuable workaround to tackle this , Could you let me know what could be the potential reason why it is happening to my case , Also I had checked version being updated in my case is the latest one being updated:- 

conda list torch

# packages in environment at C:\Users\aksho\anaconda3:
#
# Name                    Version                   Build  Channel
pytorch                   2.2.2           py3.9_cuda11.8_cudnn8_0    pytorch
pytorch-cuda              11.8                 h24eeafa_5    pytorch
pytorch-lightning         2.2.1                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
torch                     2.2.0                    pypi_0    pypi
torchaudio                2.2.0                    pypi_0    pypi
torchmetrics              1.3.2                    pypi_0    pypi
torchvision               0.17.2                   pypi_0    pypi

I tried downgrading the pytorch version to check if it supports to tackle this version bump but looks like the issue persists even then. Kindly check this and let me know if it is an open issue ?

-Kind Regards ,
Akshobhya.

**Comment by aangelopoulos** [comment]
Hey! Sorry about the issues.

The issue is likely with the `darts` package as opposed to `torch`.
`darts` is a little finicky to install depending on your system.

Based on the instructions [here](https://github.com/unit8co/darts/blob/master/INSTALL.md), can you try (in a clean environment) to replace the `darts` in `requirements.txt` with `u8darts[all]` and see if that fixes it? Hopefully, that should install the relevant version of `pytorch` as well.

**Comment by akshobhya95** [comment]
Hi aangelopoulos , Yes it worked for my case now ,thanks for the quick heads-up and suggestion!

**Comment by LukeLIN-web** [comment]
Same problem

**Comment by aangelopoulos** [comment]
@LukeLIN-web was it solved by my above comment?

**Comment by daniel-satria** [comment]
> Hey! Sorry about the issues.
> 
> The issue is likely with the `darts` package as opposed to `torch`. `darts` is a little finicky to install depending on your system.
> 
> Based on the instructions [here](https://github.com/unit8co/darts/blob/master/INSTALL.md), can you try (in a clean environment) to replace the `darts` in `requirements.txt` with `u8darts[all]` and see if that fixes it? Hopefully, that should install the relevant version of `pytorch` as well.

I had the same error in python3.12 and tried to solve with this method but to no avail.
Tried to switch to python3.11 and it worked.
Thanks!

- Operating System: Ubuntu 24.04.2 LTS              
- Kernel: Linux 6.8.0-1024-aws
